// apps/mfe-client-react-a/src/app/core/components/AppRoot.tsx
import Button from '@material-ui/core/Button';
import { MuiThemeProvider } from '@material-ui/core/styles';
import Typography from '@material-ui/core/Typography';
import React from 'react';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import styled from 'styled-components';

import { themeColours } from '@microfr/shared/ui';
import { theme } from '@microfr/shared/ui-react';
import { EvtBusEventItem, EvtBusEventType } from '@microfr/shared/util/event-bus-dom';
import { EvtBusAction, EvtBusActionType } from '@microfr/shared/util/event-bus-obs';
import { appConfig } from '../../shared/constants';
import { evtBusDom, evtBusObs } from '../../shared/helpers';

const StyledAppRoot = styled.div`
  main {
    padding: 20px;
    background-color: ${themeColours.grey300};
    text-align: center;
  }
`;

export class AppRoot extends React.Component {
  private evtBusObsDestroy: Subject<unknown> = new Subject();
  private evtBusDomItems: EvtBusEventItem[] = [];

  componentDidMount() {
    this.listenToEvtBusDom();
    this.listenToEvtBusObs();
  }

  componentWillUnmount() {
    evtBusObs.destroy(this.evtBusObsDestroy);
    evtBusDom.destroy(this.evtBusDomItems);
  }

  private listenToEvtBusDom() {
    evtBusDom.addEventListener(
      {
        type: EvtBusEventType.SampleEvent,
        listener: (event: CustomEvent) => {
          console.log(`Event to ${appConfig.label}:`, event.detail);
        },
      },
      this.evtBusDomItems
    );
  }

  private listenToEvtBusObs() {
    evtBusObs.actions$
      .pipe(takeUntil(this.evtBusObsDestroy))
      .subscribe((action: EvtBusAction) => {
        if (action && action.type === EvtBusActionType.SampleEvent) {
          console.log(`Action to ${appConfig.label}:`, action);
        }
      });
  }

  handleFooClick = () => {
    const sampleEventData = 'Fired from React App A';
    evtBusObs.dispatch({
      type: EvtBusActionType.SampleEvent,
      payload: sampleEventData,
    });
    evtBusDom.dispatch(EvtBusEventType.SampleEvent, sampleEventData);
  };

  render() {
    return (
      <MuiThemeProvider theme={theme}>
        <StyledAppRoot>
          <main>
            <Typography variant="h4" gutterBottom={true}>
              React App content: Client A
            </Typography>
            <Button variant="contained" color="primary" onClick={this.handleFooClick}>
              Test global state action
            </Button>
          </main>
        </StyledAppRoot>
      </MuiThemeProvider>
    );
  }
}

export default AppRoot;

// apps/mfe-client-ng-a/src/app/core/components/app-root/app-root.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
} from '@angular/core';
import { Router } from '@angular/router';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

import { ClientAppInfo } from '@microfr/shared/model/app-interface';
import { EvtBusEventItem, EvtBusEventType } from '@microfr/shared/util/event-bus-dom';
import { EvtBusAction, EvtBusActionType } from '@microfr/shared/util/event-bus-obs';
import { appConfig } from '../../../shared/constants';
import { EvtBusDomService, EvtBusObservablesService } from '../../../shared/services';

@Component({
  // selector: 'mfe-client-ng-a', // Element name defined as custom element on ngDoBootstrap.
  template: `
    <div class="mat-typography">
      <router-outlet></router-outlet>
    </div>
  `,
})
export class AppRootComponent implements OnInit, OnDestroy, OnChanges {
  private evtBusObsDestroy: Subject<unknown> = new Subject();
  private evtBusDomItems: EvtBusEventItem[] = [];

  @Input() appInfo: ClientAppInfo;

  constructor(
    private readonly router: Router,
    private readonly evtBusObs: EvtBusObservablesService,
    private readonly evtBusDom: EvtBusDomService
  ) {}

  ngOnInit() {
    // Bootstrapping components as Web Components requires manual router initializion.
    this.router.initialNavigation();

    this.listenToEvtBusObs();
    this.listenToEvtBusDom();
  }

  ngOnDestroy() {
    this.evtBusObs.destroy(this.evtBusObsDestroy);
    this.evtBusDom.destroy(this.evtBusDomItems);
  }

  private listenToEvtBusDom() {
    this.evtBusDom.addEventListener(
      {
        type: EvtBusEventType.SampleEvent,
        listener: (event: CustomEvent) => {
          console.log(`Event to ${appConfig.label}:`, event.detail);
        },
      },
      this.evtBusDomItems
    );
  }

  private listenToEvtBusObs() {
    this.evtBusObs.actions$
      .pipe(takeUntil(this.evtBusObsDestroy))
      .subscribe((action: EvtBusAction) => {
        if (action && action.type === EvtBusActionType.SampleEvent) {
          console.log(`Action to ${appConfig.label}:`, action);
        }
      });
  }

  ngOnChanges(changes: SimpleChanges) {
    console.log(`changes on ${appConfig.label}: `, changes);
  }
}
