// apps/mfe-client-blue/src/app/root/AppRoot.tsx
import { MuiThemeProvider } from '@material-ui/core/styles';
import React from 'react';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import './styles.scss';

import { theme } from '@microfr/shared/ui-react';
import { EvtBusEventItem, EvtBusEventType } from '@microfr/shared/util/event-bus-dom';
import { EvtBusAction, EvtBusActionType } from '@microfr/shared/util/event-bus-obs';
import { appConfig } from '../core/constants';
import { evtBusDom, evtBusObs } from '../shared/helpers';
import { ShellView } from '../views/Shell';

// TODO: implement styled components alongside SASS.
// import { themeColours } from '@microfr/shared/ui';
// import styled from 'styled-components';

export class AppRoot extends React.Component {
  private evtBusObsDestroy: Subject<unknown> = new Subject();
  private evtBusDomItems: EvtBusEventItem[] = [];

  componentDidMount() {
    this.listenToEvtBusDom();
    this.listenToEvtBusObs();
  }

  componentWillUnmount() {
    evtBusObs.destroy(this.evtBusObsDestroy);
    evtBusDom.destroy(this.evtBusDomItems);
  }

  private listenToEvtBusDom() {
    evtBusDom.addEventItem(
      {
        type: EvtBusEventType.SampleEvent,
        listener: (event: CustomEvent) => {
          console.log(`Event received by ${appConfig.label}:`, event.detail);
        },
      },
      this.evtBusDomItems
    );
  }

  private listenToEvtBusObs() {
    evtBusObs.actions$
      .pipe(takeUntil(this.evtBusObsDestroy))
      .subscribe((action: EvtBusAction) => {
        if (action) {
          console.log(`Action received by ${appConfig.label}:`, action);
        }
      });
  }

  handleFooClick = () => {
    const sampleEventData = { payload: 'Fired from React App A' };
    evtBusObs.dispatch({
      type: EvtBusActionType.SampleAction,
      payload: sampleEventData,
    });
    evtBusDom.dispatch(EvtBusEventType.SampleEvent, sampleEventData);
  };

  render() {
    return (
      <MuiThemeProvider theme={theme}>
        {/* TODO: Provide view through router */}
        {/* TODO: Apply root styles to main container custom component if possible */}
        <div className="app-root">
          <ShellView />
        </div>
      </MuiThemeProvider>
    );
  }
}

export default AppRoot;

// apps/mfe-client-ng-a/src/app/core/components/app-root/app-root.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
} from '@angular/core';
import { Router } from '@angular/router';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

import { ClientAppInfo } from '@microfr/shared/model/app-interface';
import { EvtBusEventItem, EvtBusEventType } from '@microfr/shared/util/event-bus-dom';
import { EvtBusAction, EvtBusActionType } from '@microfr/shared/util/event-bus-obs';
import { appConfig } from '../../../shared/constants';
import { EvtBusDomService, EvtBusObservablesService } from '../../../shared/services';

@Component({
  // selector: 'mfe-client-ng-a', // Element name defined as custom element on ngDoBootstrap.
  template: `
    <div class="mat-typography">
      <router-outlet></router-outlet>
    </div>
  `,
})
export class AppRootComponent implements OnInit, OnDestroy, OnChanges {
  private evtBusObsDestroy: Subject<unknown> = new Subject();
  private evtBusDomItems: EvtBusEventItem[] = [];

  @Input() appInfo: ClientAppInfo;

  constructor(
    private readonly router: Router,
    private readonly evtBusObs: EvtBusObservablesService,
    private readonly evtBusDom: EvtBusDomService
  ) {}

  ngOnInit() {
    // Bootstrapping components as Web Components requires manual router initializion.
    this.router.initialNavigation();

    this.listenToEvtBusObs();
    this.listenToEvtBusDom();
  }

  ngOnDestroy() {
    this.evtBusObs.destroy(this.evtBusObsDestroy);
    this.evtBusDom.destroy(this.evtBusDomItems);
  }

  private listenToEvtBusDom() {
    this.evtBusDom.addEventListener(
      {
        type: EvtBusEventType.SampleEvent,
        listener: (event: CustomEvent) => {
          console.log(`Event to ${appConfig.label}:`, event.detail);
        },
      },
      this.evtBusDomItems
    );
  }

  private listenToEvtBusObs() {
    this.evtBusObs.actions$
      .pipe(takeUntil(this.evtBusObsDestroy))
      .subscribe((action: EvtBusAction) => {
        if (action && action.type === EvtBusActionType.SampleEvent) {
          console.log(`Action to ${appConfig.label}:`, action);
        }
      });
  }

  ngOnChanges(changes: SimpleChanges) {
    console.log(`changes on ${appConfig.label}: `, changes);
  }
}
