// apps/mfe-client-red/src/app/features/foo-a/containers/comm-to-app/comm-to-app.component.ts
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';

import { ClientApp, OrangeAppMessage } from '@microfr/shared/model/app-interface';
import { EvtBusEventType } from '@microfr/shared/util/event-bus-dom';
import { EvtBusActionType } from '@microfr/shared/util/event-bus-obs';
import { EvtBusDomService } from '../../../../core/services/evt-bus-dom.service';
import { EvtBusObservablesService } from '../../../../core/services/evt-bus-obs.service';

@Component({
  selector: 'app-comm-to-app',
  templateUrl: './comm-to-app.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FooACommToAppComponent implements OnInit {
  constructor(
    private readonly evtBusObs: EvtBusObservablesService,
    private readonly evtBusDom: EvtBusDomService
  ) {}

  ngOnInit() {}

  onSendMessage(message: string) {
    const data: OrangeAppMessage = {
      fromApp: ClientApp.Red,
      toApp: ClientApp.Orange,
      message,
    };

    this.evtBusObs.dispatch({
      type: EvtBusActionType.SendClientOrangeMessage,
      payload: data,
    });
    this.evtBusDom.dispatch(EvtBusEventType.SendClientOrangeMessage, data);
  }
}

<app-comm-to-app-form (sendMessage)="onSendMessage($event)"></app-comm-to-app-form>

// apps/mfe-client-blue/src/app/features/foo-a/containers/CommToApp/index.tsx
import React from 'react';

import { ClientApp, OrangeAppMessage } from '@microfr/shared/model/app-interface';
import { EvtBusEventType } from '@microfr/shared/util/event-bus-dom';
import { EvtBusActionType } from '@microfr/shared/util/event-bus-obs';
import { evtBusDom, evtBusObs } from '../../../../core/helpers';
import CommToAppForm from '../../components/CommToAppForm';

export default function CommToApp() {
  function handleSendMessage(message: string) {
    const data: OrangeAppMessage = {
      toApp: ClientApp.Orange,
      fromApp: ClientApp.Blue,
      message,
    };
    evtBusObs.dispatch({
      type: EvtBusActionType.SendClientOrangeMessage,
      payload: data,
    });
    evtBusDom.dispatch(EvtBusEventType.SendClientOrangeMessage, data);
  }
  return <CommToAppForm onSendMessage={handleSendMessage} />;
}
